Zero-K.info/Models/CommentList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ZkData;

namespace ZeroKWeb.Models
{
  public class CommentList
  {
    public ForumThread Thread;
    public object ActionData;
  }
}

Zero-K.info/Controllers/BattlesController.cs
 using System;
using System.Collections.Generic;
 using System.Data.Entity;
 using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZkData;
using ZeroKWeb.Models;

namespace ZeroKWeb.Controllers
{
    public class BattlesController : Controller
    {
        //
        // GET: /Battles/

        public ActionResult Detail(int id)
        {
          var db = new ZkDataContext();
          var bat = db.SpringBattles.FirstOrDefault(x => x.SpringBattleID == id);
            if (bat == null) return Content("No such battle exists");
          if (bat.ForumThread != null)
          {
            bat.ForumThread.UpdateLastRead(Global.AccountID, false);
            db.SubmitChanges();
          }
          return View(bat);
        }

        public ActionResult Index(string battleTitle,
                                  string map,
                                  string mod,
                                  string user,
                                  int? players,
                                  int? age,
                                  int? duration,
                                  bool? mission,
                                  bool? bots,
                                  int? offset) {
            var db = new ZkDataContext();

            IQueryable<SpringBattle> q = db.SpringBattles.Include(x=>x.SpringBattlePlayers);
            
            if (!string.IsNullOrEmpty(battleTitle))
                q = q.Where(b => b.Title.Contains(battleTitle));

            if (!string.IsNullOrEmpty(map))
                q = q.Where(b => b.ResourceByMapResourceID.InternalName.Contains(map));

            if (mod == null) mod = "Zero-K";
            if (!string.IsNullOrEmpty(mod))
                q = q.Where(b => b.ResourceByModResourceID.InternalName.Contains( mod));

            //if (user == null && Global.IsAccountAuthorized) user = Global.Account.Name;
            if (!string.IsNullOrEmpty(user)) {
                var aid = (from account in db.Accounts
                          where account.Name == user
                           select account.AccountID).FirstOrDefault();
                if(aid != 0)
                    q = q.Where(b => b.SpringBattlePlayers.Any(p => !p.IsSpectator && p.AccountID == aid));
            }

            if (players.HasValue)
                q = q.Where(b => b.SpringBattlePlayers.Where(p => !p.IsSpectator).Count() == players.Value);

            if (age.HasValue) {
                DateTime limit = DateTime.UtcNow;
                switch (age) {
                    case 1:
                        limit = DateTime.Now.AddHours(-1);
                        break;
                    case 2:
                        limit = DateTime.UtcNow.AddDays(-7);
                        break;
                    case 3:
                        limit = DateTime.UtcNow.AddDays(-31);
                        break;
                }
                q = q.Where(b => b.StartTime >= limit);
            }

            if (duration.HasValue)
                q = q.Where(b => Math.Abs(b.Duration - duration.Value * 60) < 300);

            if (mission.HasValue)
                q = q.Where(b => b.IsMission == mission.Value);

            if (bots.HasValue)
                q = q.Where(b => b.HasBots == bots.Value);

            q = q.OrderByDescending(b => b.StartTime);
                

            if (offset.HasValue) q = q.Skip(offset.Value);
            q = q.Take(Global.AjaxScrollCount);

            var result = q.ToList().Select(b =>
                    new BattleQuickInfo() {
                        Battle = b,
                        Players = b.SpringBattlePlayers,
                        Map = b.ResourceByMapResourceID,
                        Mod = b.ResourceByModResourceID
                    }).ToList();


            //if(result.Count == 0)
            //    return Content("");
            if (offset.HasValue)
                return View("BattleTileList", result);
            else
                return View(result);
        }

        [Auth(Role = AuthRole.ZkAdmin)]
        public ActionResult Logs(int id)
        {
            using (var db = new ZkDataContext()) {
                var bat = db.SpringBattles.Single(x => x.SpringBattleID == id);
                return Content(System.IO.File.ReadAllText(string.Format(GlobalConst.InfologPathFormat, bat.EngineGameID)), "text/plain");//,string.Format("infolog_{0}.txt", bat.SpringBattleID)
            }
            
        }
    }

    public struct BattleQuickInfo {
        public SpringBattle Battle { get; set; }
        public IEnumerable<SpringBattlePlayer> Players { get; set; }
        public Resource Map { get; set; }
        public Resource Mod { get; set; }
    }
}

Zero-K.info/Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Transactions;
using System.Web.Mvc;
using ZeroKWeb.SpringieInterface;
using ZkData;

namespace ZeroKWeb.Controllers
{
	public class MyController: Controller
	{
		//
		// GET: /My/
		[Auth]
		public ActionResult CommanderProfile(int profileNumber, string name, int? chassis, string deleteCommander)
		{
			if (profileNumber < 1 || profileNumber > GlobalConst.CommanderProfileCount) return Content("WTF! get lost");

			var db = new ZkDataContext();
			using (var scope = new TransactionScope())
			{

				var unlocks = db.AccountUnlocks.Where(x => x.AccountID == Global.AccountID);

				Commander comm = db.Commanders.SingleOrDefault(x => x.ProfileNumber == profileNumber && x.AccountID == Global.AccountID);
				if (comm != null)
				{
					if (!string.IsNullOrEmpty(deleteCommander)) // delete commander
					{
						db.Commanders.DeleteOnSubmit(comm);
						db.SubmitChanges();
						scope.Complete();
						return GetCommanderProfileView(db, profileNumber);
					}
				}
				else
				{
					comm = new Commander() { AccountID = Global.AccountID, ProfileNumber = profileNumber };
					db.Commanders.InsertOnSubmit(comm);
				}

				if (comm.Unlock == null)
				{
					var chassisUnlock = unlocks.FirstOrDefault(x => x.UnlockID == chassis);
					if ((chassis == null || chassisUnlock == null)) return GetCommanderProfileView(db, profileNumber);
					else
					{
						comm.ChassisUnlockID = chassis.Value;
						comm.Unlock = chassisUnlock.Unlock;
					}
				}

                if (!string.IsNullOrEmpty(name))
                {
                    if (name.Length > 50) name = name.Substring(0, 50);
                    name = Regex.Replace(name, @"[^\u0000-\u007F]", string.Empty); // remove unicode stuff
                    comm.Name = name;
                }

                // process modules
				foreach (var key in Request.Form.AllKeys.Where(x => !string.IsNullOrEmpty(x)))
				{
					var m = Regex.Match(key, "m([0-9]+)");
					if (m.Success)
					{
						var slotId = int.Parse(m.Groups[1].Value);
						int unlockId;
						int.TryParse(Request.Form[key], out unlockId);

						if (unlockId > 0)
						{
							CommanderSlot slot = db.CommanderSlots.Single(x => x.CommanderSlotID == slotId);
							Unlock unlock = db.Unlocks.Single(x => x.UnlockID == unlockId);

							if (!unlocks.Any(x => x.UnlockID == unlock.UnlockID)) return Content("WTF get lost!");
							if (slot.MorphLevel < unlock.MorphLevel || slot.UnlockType != unlock.UnlockType) return Content(string.Format("WTF cannot use {0} in slot {1}", unlock.Name, slot.CommanderSlotID));
							if (!string.IsNullOrEmpty(unlock.LimitForChassis))
							{
								var validChassis = unlock.LimitForChassis.Split(',');
								if (!validChassis.Contains(comm.Unlock.Code)) return Content(string.Format("{0} cannot be used in commander {1}", unlock.Name, comm.Unlock.Name));
							}

							var comSlot = comm.CommanderModules.SingleOrDefault(x => x.SlotID == slotId);
							if (comSlot == null)
							{
								comSlot = new CommanderModule() { SlotID = slotId };
								comm.CommanderModules.Add(comSlot);
							}
							comSlot.ModuleUnlockID = unlockId;
						}
						else
						{
							var oldModule = comm.CommanderModules.FirstOrDefault(x => x.SlotID == slotId);
							if (oldModule != null) comm.CommanderModules.Remove(oldModule);
						}
					}
				}

                // process decorations
                foreach (var key in Request.Form.AllKeys.Where(x => !string.IsNullOrEmpty(x)))
                {
                    var d = Regex.Match(key, "d([0-9]+)");
                    if (d.Success)
                    {
                        var slotId = int.Parse(d.Groups[1].Value);
                        int unlockId;
                        int.TryParse(Request.Form[key], out unlockId);

                        if (unlockId > 0)
                        {
                            CommanderDecorationSlot decSlot = db.CommanderDecorationSlots.Single(x => x.CommanderDecorationSlotID == slotId);
                            Unlock unlock = db.Unlocks.Single(x => x.UnlockID == unlockId);

                            if (!unlocks.Any(x => x.UnlockID == unlock.UnlockID)) return Content("WTF get lost!");
                            if (!string.IsNullOrEmpty(unlock.LimitForChassis))
                            {
                                var validChassis = unlock.LimitForChassis.Split(',');
                                if (!validChassis.Contains(comm.Unlock.Code)) return Content(string.Format("{0} cannot be used in commander {1}", unlock.Name, comm.Unlock.Name));
                            }

                            var comSlot = comm.CommanderDecorations.SingleOrDefault(x => x.SlotID == slotId);
                            if (comSlot == null)
                            {
                                comSlot = new CommanderDecoration() { SlotID = slotId };
                                comm.CommanderDecorations.Add(comSlot);
                            }
                            comSlot.DecorationUnlockID = unlockId;
                        }
                        else
                        {
                            var oldDecoration = comm.CommanderDecorations.FirstOrDefault(x => x.SlotID == slotId);
                            if (oldDecoration != null) comm.CommanderDecorations.Remove(oldDecoration);
                        }
                    }
                }

                // remove a module/decoration if ordered to
                foreach (var toDel in Request.Form.AllKeys.Where(x => !string.IsNullOrEmpty(x)))
                {
					var m = Regex.Match(toDel, "deleteSlot([0-9]+)");
					if (m.Success)
					{
						var slotId = int.Parse(m.Groups[1].Value);
						comm.CommanderModules.Remove(comm.CommanderModules.SingleOrDefault(x => x.SlotID == slotId));
					}
                
                    var d = Regex.Match(toDel, "deleteDecorationSlot([0-9]+)");
                    if (d.Success)
                    {
                        var decSlotId = int.Parse(d.Groups[1].Value);
                        comm.CommanderDecorations.Remove(comm.CommanderDecorations.SingleOrDefault(x => x.SlotID == decSlotId));
                    }
                }

				db.SubmitChanges();
				foreach (var unlock in comm.CommanderModules.GroupBy(x => x.Unlock))
				{
					if (unlock.Key == null) continue;
					var owned = unlocks.Where(x => x.UnlockID == unlock.Key.UnlockID).Sum(x => (int?)x.Count) ?? 0;
					if (owned < unlock.Count())
					{
						var toRemove = unlock.Count() - owned;

						foreach (var m in unlock.OrderByDescending(x => x.SlotID))
						{
							db.CommanderModules.DeleteOnSubmit(m);
							//comm.CommanderModules.Remove(m);
							toRemove--;
							if (toRemove <= 0) break;
						}
					}
				}

				db.SubmitChanges();
				scope.Complete();
			}

			return GetCommanderProfileView(db, profileNumber);
		}

		[Auth]
		public ActionResult Commanders()
		{
			var db = new ZkDataContext();

			var ret = new CommandersModel();
			ret.Unlocks =
				Global.Account.AccountUnlocks.Where(
					x => x.Unlock.UnlockType != UnlockTypes.Unit).ToList
					();
			return View(ret);
		}

		public ActionResult Index()
		{
			return RedirectToAction("Detail", "Users", new { id = Global.AccountID });
		}


		public ActionResult Reset()
		{
			var db = new ZkDataContext();
			db.AccountUnlocks.DeleteAllOnSubmit(db.AccountUnlocks.Where(x => x.AccountID == Global.AccountID));
			db.SubmitChanges();
			return RedirectToAction("UnlockList");
		}

        [Auth]
        public ActionResult Unlock(int id, bool useKudos = false)
        {
            using (var db = new ZkDataContext())
            using (var scope = new TransactionScope())
            {

                List<Unlock> unlocks;
                List<Unlock> future;

                GetUnlockLists(db, out unlocks, out future);

                if (unlocks.Any(x => x.UnlockID == id))
                {
                    Unlock unlock = db.Unlocks.FirstOrDefault(x => x.UnlockID == id);
                    if (!useKudos && unlock.IsKudosOnly == true) return Content("That unlock cannot be bought using XP");

                    if (useKudos) {
                        var acc = db.Accounts.Find(Global.AccountID);
                        if (acc.Kudos < unlock.KudosCost) return Content("Not enough kudos to unlock this");
                        acc.KudosPurchases.Add(new KudosPurchase() {Time = DateTime.UtcNow, Unlock = unlock, Account = acc, KudosValue = unlock.KudosCost??0});
                        db.SubmitAndMergeChanges();
                        acc.Kudos = acc.KudosGained - acc.KudosSpent;
                        db.SubmitAndMergeChanges();
                    }
                    
                    var au = db.AccountUnlocks.SingleOrDefault(x => x.AccountID == Global.AccountID && x.UnlockID == id);
                    if (au == null)
                    {
                        au = new AccountUnlock() { AccountID = Global.AccountID, UnlockID = id, Count = 1 };
                        db.AccountUnlocks.InsertOnSubmit(au);
                    }
                    else au.Count++;
                    db.SubmitAndMergeChanges();
                }
                scope.Complete();
            }
            return RedirectToAction("UnlockList");
        }

		[Auth]
		public ActionResult UnlockList()
		{
			List<Unlock> unlocks;
			List<Unlock> future;
			var db = new ZkDataContext();
			GetUnlockLists(db, out unlocks, out future);


Zero-K.info/Views/Shared/CommentList.cshtml
@model ZeroKWeb.Models.CommentList
<div id="comments" class="border-test">
  <form method="post" action="@Url.Action("SubmitPost", "Forum", Model.ActionData ?? new { threadID = Model.Thread.ForumThreadID })">
  <textarea name="text" rows="8" cols="80"></textarea><br />
  <input class="textbutton" type="submit" value="Submit Comment" />
  </form>
  @if (Model.Thread != null) {
    @Html.Partial("~/Views/Forum/PostList.cshtml", Model.Thread.ForumPosts.OrderByDescending(x=>x.ForumPostID))
  }
</div>
<!close comments> 

Zero-K.info/Views/Shared/FactionList.cshtml
@using ZeroKWeb
@using ZkData
@{
    var db = new ZkDataContext();
}

@foreach (var f in db.Factions.Where(x => !x.IsDeleted))
{
    <div style="float:left;">
    @Html.Partial("~/Views/Factions/FactionBox.cshtml", f)
   </div>
}
<div style="clear:both;float:none"></div>

Zero-K.info/Views/Shared/GoogleSiteSearch.cshtml
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load('search', '1');
    google.setOnLoadCallback(function () 
    {
        google.search.CustomSearchControl.attachAutoCompletion(
        '005922609343212335344:hhfjrwusr9u',
        document.getElementById('q'),
        'cse-search-box');
    });
</script>
<form action="http://www.google.com/cse" id="cse-search-box">
<div>
    <input type="hidden" name="cx" value="005922609343212335344:hhfjrwusr9u" />
    <input type="hidden" name="ie" value="UTF-8" />
    <input type="text" name="q" id="q" autocomplete="off" size="20" />
    <input name="sa" value="Search" type="image" src="/img/search_img.png" style="border: none; vertical-align:middle;" />
</div>
</form>

Zero-K.info/Views/Shared/InfluenceList.cshtml
@using ZkData
@model IEnumerable<PlanetFaction>
    
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
        google.load("visualization", "1", {packages:["corechart"]});
        google.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Faction', 'Influence'],
                @foreach (var fac in Model.Where(x=>x.Influence > 0).OrderByDescending(x=>x.Influence)) {
                    <text>['@fac.Faction.Name', @fac.Influence],</text>
                }
            ['Neutral', @(100 - (Model.Sum(x=>(double?)x.Influence)??0))]
        ]);

            var options = {
                backgroundColor : 'black',
                chartArea : {left:0,top:0,width:"100%", height:"100%"},
                legend : {position:'none'},
                colors: [
                    
                    @foreach (var fac in Model.Where(x=>x.Influence > 0).OrderByDescending(x=>x.Influence)) {
                        <text>'@fac.Faction.Color',</text>
                    }
                
            '#808080'
        ]
            
        };

        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        }
    </script>    
    
<div id="chart_div" style="width: 200px; height: 200px; float:left"></div>    

<table>
    @foreach (var facGroup in Model.Where(x=>x.Influence > 0).OrderByDescending(g => g.Influence))
    {
        <tr>
            <td>
                <b><img src='@facGroup.Faction.GetImageUrl()' style='width: 32px; height: 32px;'/></b>
            </td>
            <td>
                <b>
                    @Html.PrintInfluence(facGroup.Faction, facGroup.Influence)
                </b>
            </td>
        </tr>
    }
</table>
<br style="clear:both"/>

Zero-K.info/Views/Shared/InfluenceListShort.cshtml
@using ZkData
@model IEnumerable<PlanetFaction>

<table>

    @foreach (var facGroup in Model.Where(x=>x.Influence > 0).OrderByDescending(g => g.Influence))
    {
        <tr>
            <td>
                <b><img src='@facGroup.Faction.GetImageUrl()' style='width: 32px; height: 32px;'/></b>
            </td>
            <td>
                <b>
                    @Html.PrintInfluence(facGroup.Faction, facGroup.Influence)
                </b>
            </td>
        </tr>
    }
</table>

Zero-K.info/Views/Shared/LoginBar.cshtml
 @using ZeroKWeb
@if (!Global.IsLobbyAccess || Global.IsAccountAuthorized)
{

    if (!(Global.IsAccountAuthorized))
    {
@*<!login>*@
    <form method="post" action="@Url.Action("Logon", "Home")" style="padding: 0; margin: 0;" >
    Name:
    <input type="text" name="login" />
    &nbsp;&nbsp; Password:
    <input type="password" name="password" />
    &nbsp;&nbsp;
    <input type="image" value="Login" src="/img/login.png" style="border: none; width: 25px;
        height: 25px; vertical-align: middle;" title="Login with your Zero-K lobby account" alt="Login" />
        <small>
        (<a href="/Wiki/FAQ#11._I_forgot_my_password_/_username._Help_me_pls!" target="_blank">Forgot password / username?</a> /
        <a href="/Wiki/LobbyStart" target="_blank">Create an account</a>)
        </small>
    <input type="hidden" name="referer" value="@(Request["ReturnUrl"] != null ? Request["ReturnUrl"] : Request.Url.ToString())" />
    </form>        
    }
    else
    {        
    <form method="post" action="@Url.Action("Logout", "Home")@(Global.IsLobbyAccess ? "@logout" : "")"  style="padding: 0; margin: 0; display:inline" >
    @Html.PrintAccount(Global.Account)
        <input type="hidden" name="referer" value="@Request.Url" /> | @Html.PrintClan(Global.Clan) | @Html.PrintFaction(Global.Account.Faction, false) | <span nicetitle="Your level based on experience">Level: @Global.Account.Level</span> | <span nicetitle="Points available to spend on commander unlocks">Tech Points: @Global.Account.AvailableXP</span> | <span nicetitle="Metagame currency that you can get by donating to Zero-K. You can use it to get access to unique commander decorations">Kudos: @Global.Account.Kudos</span> | @Html.PrintMetal(Global.Account) | @Html.PrintDropships(Global.Account) | @Html.PrintBombers(Global.Account) | @Html.PrintWarps(Global.Account) | Logout 
    <input type="image" value="Logout" src="/img/logout.png" style="border: none; width: 25px;
        height: 25px; vertical-align: middle;" alt="Logout" title="Logout" />
    </form>
    //if not using zklobby
        if (!Global.IsLobbyAccess)
        {
    <div align="right" style="vertical-align: middle; display:block; float:right; padding:5px;"><a href="@Url.Action("SwitchSkin","Home")" title="Switch to an alternative skin"><img style="vertical-align: middle;" align="right" src="/img/switch_skin.png" alt="Switch skin" /></a>
    </div>
        }
    }
}

Zero-K.info/Views/Shared/PlanetDropships.cshtml
@model ZkData.Planet
         
<table>
  @foreach (var p in Model.PlanetFactions.Where(x => x.Dropships > 0).OrderByDescending(x => x.Dropships)) { 
    <tr>
      <td>@Html.PrintFaction(p.Faction, false)
      </td>
      <td><img src='@p.Faction.GetShipImageUrl()' />@p.Dropships</td>
    </tr>
  }
</table>

Zero-K.info/Views/Shared/PlanetIcon.cshtml
@using ZkData
@model Planet
@{         
    var planetIconUrl = "/img/planets/" + Model.Resource.MapPlanetWarsIcon;
    var size = Model.Resource.PlanetWarsIconSize * Planet.OverlayRatio;
    var offset = (Model.Resource.PlanetWarsIconSize * Planet.OverlayRatio - Model.Resource.PlanetWarsIconSize) / 2;
}
<span style='width: @(size)px; height:@(size)px; display: inline-block;'>
  <img src='@planetIconUrl' width='@(Model.Resource.PlanetWarsIconSize)' style='position:absolute; padding-left: @(offset)px; padding-top: @(offset)px' />
  @foreach (var s in Model.PlanetStructures)
  {
    <img src='@s.GetImageUrl()' width='@size' style='position:absolute' />
  }
</span>

Zero-K.info/Views/Shared/PlanetIconCampaign.cshtml
@using ZkData
@model CampaignPlanet
@{
    var db = new ZkDataContext();
    string mapName = Model.DisplayedMap ?? Model.Mission.Map;
    Resource map = db.Resources.FirstOrDefault(m => m.InternalName == mapName);
    var planetIconUrl = "/img/planets/" + map.MapPlanetWarsIcon;
    var size = map.PlanetWarsIconSize * CampaignPlanet.OverlayRatio;
    var offset = (map.PlanetWarsIconSize * CampaignPlanet.OverlayRatio - Model.Mission.Resources.First().PlanetWarsIconSize) / 2;
}
<span style='width: @(size)px; height:@(size)px; display: inline-block;'>
  <img src='@planetIconUrl' width='@(map.PlanetWarsIconSize)' style='position:absolute; padding-left: @(offset)px; padding-top: @(offset)px' />
</span>

Zero-K.info/Views/Shared/TopMenu.cshtml
@using ZeroKWeb
  <table>
      <tr>
          <td>
              <ul class="menu">
                  <li><a href="@Url.Action("Index", "Home")">Home</a>
                      <ul>
                          <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                          <li><a href="@Url.Action("UnlockList", "My")">Unlocks</a></li>
                          <li><a href="@Url.Action("Commanders", "My")">Commanders</a></li>
                          <li><a href="@Url.Action("UserVotes", "Poll", new{id = Global.AccountID})">Polls</a></li>
                      </ul>
                  </li>
              </ul>
          </td>
          <td>
              <ul class="menu">
                  <li><a href="/Wiki/Download">Play</a>
                      <ul>
                          <li><a href="/Wiki/Download">Download Zero-K<span>Download the game, it's free! :)</span></a></li>
                          <li><a href="@Url.Action("Index", "Missions")">Missions<span>Single player missions</span></a></li>
                          <li><a href="@Url.Action("Index", "Maps")">Maps<span>Thousands of maps to pick</span></a></li>
                          <li><a href="@Url.Action("Index", "Battles")">Replays<span>All your past victories, stored here!</span></a></li>
                      </ul>
                  </li>
              </ul>
          </td>
          <td>
              <ul class="menu">
                  <li><a href="/Wiki/Media">Media</a>
                      <ul>
                          <li><a href="/Wiki/Media#Screenshots">Screenshots</a></li>
                          <li><a href="/Wiki/Media#Videos">Videos</a></li>
                          <li><a href="/Wiki/Fanart">Fanart<span>Show the world your favorite game ;-)</span></a></li>
                      </ul>
                  </li>
              </ul>
          </td>
          <td>
              <ul class="menu">
                  <li><a href="/Wiki/Manual">Manual</a>
                      <ul>
                          <li><a href="/Wiki/Manual">Index</a></li>
                          <li><a href="/Wiki/NewbieGuide">Newbie guide<span>Don't know where to begin? Click
                                                                          here.</span></a></li>
                          <li><a href="/Static/UnitGuide">Units</a></li>
                          <li><a href="/Wiki/EconomyGuide">Economy</a></li>
                          <li><a href="/Wiki/Terraforming">Terraforming<span>Let's go play in the dirt!</span></a></li>
                          <li><a href="/Wiki/FAQ">FAQ<span>Frequently Asked Questions</span></a></li>
                      </ul>
                  </li>
              </ul>
          </td>
          <td>
              <ul class="menu">
                  <li><a href="@Url.Action("Index", "Planetwars")">PlanetWars</a>
                      <ul>
                          <li><a href="@Url.Action("Index", "Planetwars")">PlanetWars<span>Multiplayer online campaign</span></a></li>
                          <li><a href="@Url.Action("Ladder", "Planetwars")">Ladder</a></li>
                          <li><a href="@Url.Action("Index", "Factions")">Factions<span>The mighty factions controlling huge sectors of galaxy</span></a></li>
                      </ul>
                  </li>
              </ul>
          </td>
          <td>
              <ul class="menu">
                  <li><a href="@Url.Action("Index", "Forum")">Community</a>
                      <ul>
                          <li><a href="@Url.Action("Index", "Forum")">Forum<span>Discuss, ask for help, have fun!</span></a></li>
                          <li><a href="@Url.Action("Index", "Clans")">Clans<span>Play with your friends or make friends while playing :)</span></a></li>
                          <li><a href="@Url.Action("Index", "Ladders")">Ladders</a></li>
                          <li><a href="@Url.Action("Index", "Users")">Users<span>Find a player</span></a></li>
                          <li><a href="/Wiki/CodeOfConduct">Code of Conduct<span>Be nice, have fun!</span></a></li>
                          <li><a target="_new" href="https://github.com/ZeroK-RTS/">Develop<span>Make the game with us</span></a></li>
                          <li><a href="/Wiki/PrivacyPolicy">Privacy Policy</a></li>
                          <li><a href="/Wiki/Credits">Credits<span>Makers of Zero-K</span></a></li>
                      </ul>
                  </li>
              </ul>
          </td>
          <td>
              <ul class="menu">
                  <li><a href="@Url.Action("Index","Contributions")">Donate<span>Help cover the server costs!</span></a>
                  </li>
              </ul>
          </td>
          
          <td width="100%">
              @{ Html.RenderPartial("GoogleSiteSearch"); }
          </td>
      </tr>
  </table>

Zero-K.info/Views/Shared/UnlockedTechnologies.cshtml
 @model IEnumerable<ZkData.AccountUnlock>
<div>
@foreach (var au in Model) {
  var unlock = au.Unlock;
  <div style="color: @unlock.LabelColor; font-size:x-small; text-align: center; float: left; width:90px; height:105px; position: relative;" title="$unlock$@unlock.UnlockID"  >
    <img src="@unlock.ImageUrl"/><br />
    @if (au.Count > 1) { 
      <big>@au.Count x</big>
    }
    @unlock.Name
  </div>
}
<br class="clearfloat" />
</div>

Zero-K.info/Views/Shared/_AjaxLayout.cshtml
@RenderBody()