Zero-K.info/Controllers/LaddersController.cs
using System;
using System.Collections.Generic;
﻿using System.Data.Entity;
﻿using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Helpers;
using System.Web.Mvc;
﻿using Microsoft.Linq.Translations;
﻿using ZkData;

namespace ZeroKWeb.Controllers
{
	public class LaddersController: Controller
	{
	    public class GameStats {
	        public DateTime Day { get; set; }
	        public int PlayersAndSpecs { get; set; }
	        public int MinutesPerPlayer { get; set; }
	        public int FirstGamePlayers { get; set; }
	    }

	    [OutputCache(Duration = 3600*2)]
	    public ActionResult Games() {

	        var db = new ZkDataContext();
	        db.Database.CommandTimeout = 600;
            
	        var data = (List<GameStats>)HttpContext.Cache.Get("gameStats");
	        if (data == null) {

	            var start = new DateTime(2011, 2, 3);
	            var end = DateTime.Now.Date;
                data = (from bat in db.SpringBattles
	                    where bat.StartTime < end && bat.StartTime > start
	                    group bat by DbFunctions.TruncateTime(bat.StartTime)
	                    into x orderby x.Key
	                    let players = x.SelectMany(y => y.SpringBattlePlayers.Where(z => !z.IsSpectator)).Select(z => z.AccountID).Distinct().Count()
	                    select
	                        new GameStats
	                        {
	                            Day = x.Key.Value, 
	                            PlayersAndSpecs = x.SelectMany(y => y.SpringBattlePlayers).Select(z => z.AccountID).Distinct().Count(),
	                            MinutesPerPlayer = x.Sum(y => y.Duration*y.PlayerCount)/60/players,
	                            FirstGamePlayers =
	                                x.SelectMany(y => y.SpringBattlePlayers)
	                                 .GroupBy(y => y.Account)
	                                 .Count(y => y.Any(z => z == y.Key.SpringBattlePlayers.FirstOrDefault()))
	                        }).ToList();

                HttpContext.Cache.Add("gameStats", data, null, DateTime.Now.AddHours(20), System.Web.Caching.Cache.NoSlidingExpiration, System.Web.Caching.CacheItemPriority.Default, null);
	        }
            
			var chart = new Chart(1500, 700, ChartTheme.Blue);

			chart.AddTitle("Daily activity");
			chart.AddLegend("Daily values", "dps");

			chart.AddSeries("unique players+specs", "Line", xValue: data.Select(x => x.Day).ToList(), yValues: data.Select(x => x.PlayersAndSpecs).ToList(), legend: "dps");
			chart.AddSeries("minutes/player", "Line", xValue: data.Select(x => x.Day).ToList(), yValues: data.Select(x => x.MinutesPerPlayer).ToList(), legend: "dps");
			chart.AddSeries("new players", "Line", xValue: data.Select(x => x.Day).ToList(), yValues: data.Select(x => x.FirstGamePlayers).ToList(), legend: "dps");

            return File(chart.GetBytes("png"), "image/png");
		}

        private LadderModel GetLadder()
        {
            LadderModel cached = (LadderModel)HttpContext.Cache.Get("ladderModel");
            if (cached != null) {
                return cached;
            }

            var db = new ZkDataContext();
            db.Database.CommandTimeout = 600;

            var monthStart = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
            var validAwards = db.SpringBattles.Where(x => x.StartTime >= monthStart && !x.ResourceByMapResourceID.InternalName.Contains("SpeedMetal")).SelectMany(x => x.AccountBattleAwards).GroupBy(x => x.AwardKey);

            var awardItems = new List<AwardItem>();

            foreach (var awardsByType in validAwards)
            {
                var awardType = awardsByType.Key;

                var awardCounts = awardsByType.GroupBy(x => x.Account).Select(x => new { Account = x.Key, Count = x.Count() }).OrderByDescending(x => x.Count);

                var topCountM = awardCounts.First().Count;
                var topCollectorsM = new List<Account>();
                foreach (var award in awardCounts)
                {
                    if (award.Count == topCountM) topCollectorsM.Add(award.Account);
                    else break;
                }



                var topScore = 0;
                string titleName = null;

                topScore = 0;
                var fullTitleM = "";
                int topActID = 0;
                int topBattleID = 0;
                foreach (var award in awardsByType)
                {
                    if (titleName == null) titleName = award.AwardDescription.Split(',').First();
                    int score;
                    if (int.TryParse(Regex.Replace(award.AwardDescription, @"\D", String.Empty), out score))
                    {
                        if (score > topScore)
                        {
                            topActID = award.AccountID;
                            topBattleID = award.SpringBattleID;
                            topScore = score;
                            fullTitleM = string.Join(" ", award.AwardDescription.Split(',').Skip(1));
                        }
                    }
                }

                var awardItem = new AwardItem
                {
                    AwardType = awardType,
                    AwardTitle = titleName,
                    TopScoreHolderM = db.Accounts.SingleOrDefault(x => x.AccountID == topActID),
                    TopScoreDescM = fullTitleM,
                    TopScoreBattlePlayerM = db.SpringBattlePlayers.SingleOrDefault(x => x.AccountID == topActID && x.SpringBattleID == topBattleID),
                    TopCollectorsM = topCollectorsM,
                    TopCollectorCountM = topCountM,
                };
                awardItems.Add(awardItem);
            }

            var lastMonth = DateTime.UtcNow.AddMonths(-1);
            var top50Accounts =
                db.Accounts.Where(x => x.SpringBattlePlayers.Any(y => y.SpringBattle.StartTime > lastMonth)).Include(x=>x.Clan).Include(x=>x.Faction).OrderByDescending(x => x.Effective1v1Elo).WithTranslations().Take(50).ToList();

            var top50Teams =
                db.Accounts.Where(x => x.SpringBattlePlayers.Any(y => y.SpringBattle.StartTime > lastMonth)).Include(x => x.Clan).Include(x => x.Faction).OrderByDescending(x => x.EffectiveElo).WithTranslations().Take(50).ToList();

            LadderModel ladder = new LadderModel { AwardItems = awardItems, Top50Accounts = top50Accounts, Top50Teams = top50Teams };
            HttpContext.Cache.Add("ladderModel", ladder, null, DateTime.Now.AddHours(2), System.Web.Caching.Cache.NoSlidingExpiration, System.Web.Caching.CacheItemPriority.Default, null);

            return new LadderModel { AwardItems = awardItems, Top50Accounts = top50Accounts, Top50Teams = top50Teams };
        }
		//
		// GET: /Ladders/
		public ActionResult Index()
		{
            var ladderModel = GetLadder();
			return View("Ladders", ladderModel);
		}


		public class AwardItem
		{
			public string AwardTitle;
			public string AwardType;

			//for all time
			public int TopCollectorCount;


			//for this month
			public int TopCollectorCountM;
			public List<Account> TopCollectors;
			public List<Account> TopCollectorsM;
			public SpringBattlePlayer TopScoreBattlePlayer;
			public SpringBattlePlayer TopScoreBattlePlayerM;
			public string TopScoreDesc;
			public string TopScoreDescM;
			public Account TopScoreHolder;
			public Account TopScoreHolderM;
		}

		public class LadderModel
		{
			public List<AwardItem> AwardItems;
			public List<Account> Top50Accounts;
            public List<Account> Top50Teams;
		}
	}
}

Zero-K.info/Controllers/PlanetwarsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Transactions;
using System.Web.Mvc;
using ZkData;

namespace ZeroKWeb.Controllers
{
    public class PlanetwarsController : Controller
    {
        //
        // GET: /Planetwars/
        [Auth]
        public ActionResult BombPlanet(int planetID, int count, bool? useWarp)
        {
            var db = new ZkDataContext();
            Account acc = db.Accounts.Single(x => x.AccountID == Global.AccountID);
            if (acc.Faction == null) return Content("Join some faction first");
            Planet planet = db.Planets.Single(x => x.PlanetID == planetID);
            bool accessible = (useWarp == true) ? planet.CanBombersWarp(acc.Faction) : planet.CanBombersAttack(acc.Faction);
            if (!accessible) return Content("You cannot attack here");
            if (Global.Nightwatch.GetPlanetBattles(planet).Any(x => x.IsInGame)) return Content("Battle in progress on the planet, cannot bomb planet");

            bool selfbomb = acc.FactionID == planet.OwnerFactionID;
            if (count < 0) count = 0;
            double avail = Math.Min(count, acc.GetBombersAvailable());
            if (useWarp == true) avail = Math.Min(acc.GetWarpAvailable(), avail);

            var capa = acc.GetBomberCapacity();
            if (avail > capa) return Content("Too many bombers, increase bomber fleet size capacity");

            if (avail > 0)
            {
                double defense = planet.PlanetStructures.Where(x => x.IsActive).Sum(x => x.StructureType.EffectBomberDefense) ?? 0;
                double effective = avail;
                if (!selfbomb) effective = effective - defense;

                if (effective <= 0) return Content("Enemy defenses completely block your ships");

                acc.SpendBombers(avail);
                if (useWarp == true) acc.SpendWarps(avail);

                var r = new Random();

                double strucKillChance = !selfbomb ? effective * GlobalConst.BomberKillStructureChance : 0;
                int strucKillCount = (int)Math.Floor(strucKillChance + r.NextDouble());

                double ipKillChance = effective * GlobalConst.BomberKillIpChance;
                int ipKillCount = (int)Math.Floor(ipKillChance + r.NextDouble());

                List<PlanetStructure> structs = planet.PlanetStructures.Where(x => x.StructureType.IsBomberDestructible).ToList();
                var bombed = new List<PlanetStructure>();
                while (structs.Count > 0 && strucKillCount > 0)
                {
                    strucKillCount--;
                    PlanetStructure s = structs[r.Next(structs.Count)];
                    bombed.Add(s);
                    structs.Remove(s);
                    db.PlanetStructures.DeleteOnSubmit(s);
                }

                double ipKillAmmount = ipKillCount * GlobalConst.BomberKillIpAmount;
                if (ipKillAmmount > 0)
                {
                    foreach (PlanetFaction pf in planet.PlanetFactions.Where(x => x.FactionID != acc.FactionID))
                    {
                        pf.Influence -= ipKillAmmount;
                        if (pf.Influence < 0) pf.Influence = 0;
                    }
                }

                var args = new List<object>
                           {
                               acc,
                               acc.Faction,
                               !selfbomb ? planet.Faction : null,
                               planet,
                               avail,
                               defense,
                               useWarp == true ? "They attacked by warp. " : "",
                               ipKillAmmount
                           };
                args.AddRange(bombed.Select(x => x.StructureType));

                string str;
                if (selfbomb) str = "{0} of {1} bombed own planet {3} using {4} bombers against {5} defenses. {6}Ground armies lost {7} influence";
                else str = "{0} of {1} bombed {2} planet {3} using {4} bombers against {5} defenses. {6}Ground armies lost {7} influence";
                if (bombed.Count > 1)
                {
                    str += " and ";
                    int counter = 8;
                    foreach (PlanetStructure b in bombed)
                    {
                        str += "{" + counter + "}" + ", ";
                        counter++;
                    }
                    str += " were destroyed.";
                }
                else if (bombed.Count == 1)
                {
                    str += " and {8} was destroyed.";
                }
                else str += ".";

                db.Events.InsertOnSubmit(Global.CreateEvent(str, args.ToArray()));
            }

            db.SubmitAndMergeChanges();
            SetPlanetOwners();
            return RedirectToAction("Planet", new { id = planetID });
        }

        [Auth]
        public ActionResult BuildStructure(int planetID, int structureTypeID)
        {
            using (var db = new ZkDataContext())
            {
                Planet planet = db.Planets.Single(p => p.PlanetID == planetID);
                if (Global.Nightwatch.GetPlanetBattles(planet).Any(x => x.IsInGame)) return Content("Battle in progress on the planet, cannot build structures");
                Account acc = db.Accounts.Single(x => x.AccountID == Global.AccountID);
                if (acc.FactionID != planet.OwnerFactionID) return Content("Planet is not under your control.");

                StructureType structureType = db.StructureTypes.SingleOrDefault(s => s.StructureTypeID == structureTypeID);
                if (structureType == null) return Content("Structure type does not exist.");
                if (!structureType.IsBuildable) return Content("Structure is not buildable.");

                if (acc.GetMetalAvailable() < structureType.Cost) return Content("Insufficient metal");
                acc.SpendMetal(structureType.Cost);

                var newBuilding = new PlanetStructure
                                  {
                                      StructureTypeID = structureTypeID,
                                      PlanetID = planetID,
                                      OwnerAccountID = acc.AccountID,
                                      IsActive = false,
                                      ActivatedOnTurn = planet.Galaxy.Turn
                                  };
                db.PlanetStructures.InsertOnSubmit(newBuilding);
                db.SubmitChanges();

                db.Events.InsertOnSubmit(Global.CreateEvent("{0} has built a {1} on {2} planet {3}.",
                                                            Global.Account,
                                                            newBuilding.StructureType,
                                                            planet.Faction,
                                                            planet));
                SetPlanetOwners(db);
            }
            return RedirectToAction("Planet", new { id = planetID });
        }

        [Auth]
        public ActionResult DestroyStructure(int planetID, int structureTypeID)
        {
            using (var db = new ZkDataContext())
            {
                Planet planet = db.Planets.Single(p => p.PlanetID == planetID);
                if (Global.Nightwatch.GetPlanetBattles(planet).Any(x => x.IsInGame)) return Content("Battle in progress on the planet, cannot destroy structures");
                Account acc = db.Accounts.Single(x => x.AccountID == Global.AccountID);
                StructureType structureType = db.StructureTypes.SingleOrDefault(s => s.StructureTypeID == structureTypeID);
                Faction faction = planet.Faction;
                if (structureType == null) return Content("Structure type does not exist.");
                if (!structureType.IsBuildable) return Content("Structure is not buildable.");

                // assumes you can only build level 1 structures! if higher level structures can be built directly, we should check down the upgrade chain too

                if (!planet.PlanetStructures.Any(x => x.StructureTypeID == structureTypeID)) return Content("Structure or its upgrades not present");

                List<PlanetStructure> list = planet.PlanetStructures.Where(x => x.StructureTypeID == structureTypeID).ToList();
                PlanetStructure toDestroy = list[0];
                var canDestroy = toDestroy.OwnerAccountID == acc.AccountID || planet.OwnerAccountID == acc.AccountID;
                if (!canDestroy) return Content("Structure is not under your control.");
                db.PlanetStructures.DeleteOnSubmit(toDestroy);
                var refund = toDestroy.StructureType.Cost * GlobalConst.SelfDestructRefund;
                if (toDestroy.Account != null) toDestroy.Account.ProduceMetal(refund);
                else faction.ProduceMetal(refund);
                db.Events.InsertOnSubmit(Global.CreateEvent("{0} has demolished a {1} on {2}.", Global.Account, toDestroy.StructureType, planet));
                db.SubmitChanges();
                SetPlanetOwners(db);
            }

            return RedirectToAction("Planet", new { id = planetID });
        }


        public ActionResult Events(int? planetID,
                                   int? accountID,
                                   int? springBattleID,
                                   int? clanID,
                                   int? factionID,
                                   string filter,
                                   int pageSize = 0,
                                   int page = 0,

Zero-K.info/Views/Planetwars/ClanDiplomacy.cshtml
 @using ZeroKWeb
@using ZkData
@model Clan
         
@{
    Page.Title = Model.ClanName + " - " + Model.Shortcut + " clan diplomacy";
    var c = Model;
    var isMember = c.Accounts.Any(y => y.AccountID == Global.AccountID);

}

<div>


    @if (Global.Clan != null && (Global.Account.IsClanFounder || Global.Account.HasClanRights) && Global.ClanID != Model.ClanID)
    {
        <h3>@Global.Clan.ClanName diplomatic releationship with @Model.ClanName</h3>
        
        var our = Global.Clan.TreatyOffersByOfferingClanID.SingleOrDefault(x => x.TargetClanID == Model.ClanID) ?? new TreatyOffer();
        var their = Model.TreatyOffersByOfferingClanID.SingleOrDefault(x => x.TargetClanID == c.ClanID) ?? new TreatyOffer();
        var effective = Global.Clan.GetEffectiveTreaty(Model);
        <table>

            <tr>
                <td colspan='2'><b>@Html.PrintClan(Model) - <span style='color:@Clan.AllyStatusColor(effective.AllyStatus)'>@Model.ClanName</span> - @Html.PrintTreaty(effective) </b>
                </td>
            </tr>
            <tr>
                <td valign='top'>
                    <form method="post" action="@Url.Action("OfferTreaty", new { targetClanID = Model.ClanID })">
                        @Html.PrintTreaty(our)<br />
                        Status: @Html.DropDownList("ourStatus", Enum.GetValues(typeof(AllyStatus)).OfType<AllyStatus>().Select(x => new SelectListItem() { Text = x.ToString(), Value = ((int)x).ToString(), Selected = our.AllyStatus == x }))
                        Research: @Html.CheckBox("ourResearch", our.IsResearchAgreement)<input type="submit" value="offer"/><br />
                        WARNING: If your ally or ceasefire partner owns the planet where you fought after battle, you give all your influence there to him/her!<br />
                    </form>
                </td>    

                <td valign='top'>
                    <span>
                        @Html.PrintTreaty(their)<br />
                    </span>
                </td>

            </tr>
        </table>
    }


    <h3>@Model.ClanName diplomacy</h3>
    <table>
        <tr>
            <td>Our offer</td>
            <td>Their offer</td>
        </tr>
        @foreach (var them in new ZkDataContext().AccountPlanets.GroupBy(x => x.Account.Clan).Where(x => x.Key != null && x.Key.ClanID != Model.ClanID && !x.Key.IsDeleted).Select(x => new { Clan = x.Key, Influence = x.Sum(y => (int?)y.Influence) ?? 0 }).Where(x => x.Influence > 0).OrderByDescending(x => x.Influence).Select(x => x.Clan))
        {
            var our = c.TreatyOffersByOfferingClanID.SingleOrDefault(x => x.TargetClanID == them.ClanID) ?? new TreatyOffer();
            var their = them.TreatyOffersByOfferingClanID.SingleOrDefault(x => x.TargetClanID == c.ClanID) ?? new TreatyOffer();
            var effective = Model.GetEffectiveTreaty(them);

            <tr>
                <td colspan='2'><b>@Html.PrintClan(them) - <span style='color:@Clan.AllyStatusColor(effective.AllyStatus)'>@them.ClanName</span> - @Html.PrintTreaty(effective) </b>
                </td>
            </tr>

            <tr>
                <td valign='top'>
                    @if (isMember)
                    {
                        if (Global.Account.HasClanRights)
                        {
                            <form method="post" action="@Url.Action("OfferTreaty", new { targetClanID = them.ClanID })">
                                @Html.PrintTreaty(our)<br />
                                Status: @Html.DropDownList("ourStatus", Enum.GetValues(typeof(AllyStatus)).OfType<AllyStatus>().Select(x => new SelectListItem() { Text = x.ToString(), Value = ((int)x).ToString(), Selected = our.AllyStatus == x }))
                                Research: @Html.CheckBox("ourResearch", our.IsResearchAgreement)<input type="submit" value="offer"/><br />
                            </form>
                        }
                        else
                        {
                            <span>
                                @Html.PrintTreaty(our)<br />
                            </span>
                        }
                    }
                    else
                    {
                        <span>
                            @Html.PrintTreaty(our)
                            <br />
                        </span>
                    }
                </td>
                <td valign='top'>
                    <span>
                        @Html.PrintTreaty(their)<br />
                    </span>
                </td>
            </tr>
        }
    </table>

</div>

Zero-K.info/Views/Planetwars/ClanList.cshtml
@using ZkData
@using ZeroKWeb
@model IQueryable<Clan>
@{
  Page.Title = "List of PlanetWars clans";
}
<script type="text/javascript" language="javascript">
  $(document).ready(function () {
    $('#clanTable').tablesorter({
      sortList: [[3, 1]]
    });
    
  }); 
</script>
@Html.Partial("FactionList")
<br />

@if (Global.Clan == null) {
<div>
To take a full part in <a href='@Url.Action("Index", "Planetwars")'>PlanetWars</a> join a clan. <br />
You can also @Html.ActionLink("create new clan", "CreateClan", "Planetwars")<br />
Clan size is normally limited to @GlobalConst.MaxClanSkilledSize people.
</div>
}


<table id="clanTable" class="tablesorter">
  <thead style="cursor:pointer">
    <tr>
      <th>Full name</th>
      <th>Faction</th>
      <th>
        Tag
      </th>
      <th>Planets</th>
      <th>
        Influence
      </th>
      <th>Credits</th>
      <th>Dropships</th>
      <th>
        Leader
      </th>
      <th>
        Commanders
      </th>
      <th>Elo (avg)</th>
      <th>Level (med)</th>
      @if (Global.Account == null) {
      <th>
        Can join?
      </th>
      }
    </tr>
  </thead>
  <tbody>

  @foreach (var c in Model) {
    <tr>
    <td><a href='@Url.Action("Clan", new {id= c.ClanID})'><img src='@c.GetImageUrl()' />@c.ClanName</a></td>
      <td>@Html.PrintFaction(c.Faction)</td>
	  <td>@Html.PrintClan(c)</td>
      <td>@c.Accounts.Sum(x=>x.Planets.Count())</td>
      <td>@c.Accounts.SelectMany(x=>x.AccountPlanets).Sum(x=>(int?)x.Influence)</td>
      <td>@c.Accounts.Sum(x=>x.Credits)</td>
      <td>@c.Accounts.Sum(x=>x.DropshipCount)</td>
      <td>@Html.PrintAccount(c.Accounts.SingleOrDefault(x=>x.IsClanFounder))</td>
      <td>@c.Accounts.Count()</td>
      <td>@Math.Round(c.Accounts.Average(x=>x.EffectiveElo))</td>
      <td>@c.Accounts.OrderBy(x=>x.Level).Skip(c.Accounts.Count()/2).First().Level</td>
      
      @if (Global.Clan == null) {
        if (c.CanJoin(Global.Account)) {
        <td><span class="textbutton">@Html.ActionLink("Join now!", "JoinClan", new { id = c.ClanID }, new { @class = "delete" })</span> @(string.IsNullOrEmpty(c.Password) ? "" : "password")</td>
        } else {
        <td>Full or different faction</td>
        }
      }
      
    </tr>
   }
   </tbody>
</table>

Zero-K.info/Views/Planetwars/CreateClan.cshtml
@using PlasmaShared
@using ZeroKWeb
@using ZkData
@model Clan
<form method="post" action="@Url.Action("SubmitCreateClan")" enctype="multipart/form-data">
@Html.HiddenFor(x=>x.ClanID)
  @if (Model.ClanID > 0)
   {      @Html.HiddenFor(x=>x.FactionID)   }
<table>
  <tr>
    <td>
      Name:<br/>
      WARNING: for consistency reasons make sure it matches theme of planetwars and the faction you choose
    </td>
    <td>
    @Html.TextBoxFor(x => x.ClanName, new { maxlength = 50 })
    </td>
  </tr>
  <tr>
    <td>
      Shortcut:
    </td>
    <td>
      @Html.TextBoxFor(x=>x.Shortcut, new { maxlength = 6})
    </td>
  </tr>
  
  @if (Model.ClanID == 0)
   {
       <tr><td>Faction:</td>
           <td>@Html.DropDownListFor(x => x.FactionID, new ZkDataContext().Factions.Shuffle().Select(x => new SelectListItem() { Text = x.Name, Value = x.FactionID.ToString(), Selected = x.FactionID == Model.FactionID }))  <a href='http://zero-k.info/Wiki/PlanetWarsFactions'>read more</a></td>
       </tr>
   }
      

  <tr>
  <td>Leader title:</td>
  <td>@Html.TextBoxFor(x=>x.LeaderTitle, new {maxlength=50})</td>
  </tr>
  <tr>
    <td>
      Password (leave blank to allow any to join):
    </td>
    <td>@Html.TextBoxFor(x=>x.Password)
    </td>
  </tr>
  <tr>
    <td>
      Image (64x64 png with transparency):<br/>>
      WARNING: for consistency reasons make sure it matches color of the faciton and is thematically matching (no troll face or cat if you are killer robots faction :-)
    </td>
    <td>
      <img src='@Model.GetImageUrl()' />
      <input type="file" name="image" />
    </td>
  </tr>
  <tr>
    <td>
      Background Image for your clan page (png with transparency):
    </td>
    <td>
      <img src='@Model.GetBGImageUrl()' width='128px' />
      <input type="file" name="bgimage" />
    </td>
  </tr>
  <tr>
    <td>
      Topic (internal info):
    </td>
    <td>
      @Html.TextAreaFor(x=>x.SecretTopic, 4,40, null)
    </td>
  </tr>
  <tr>
    <td>
      Description (public):
    </td>
    <td>
      @Html.TextAreaFor(x=>x.Description,4,40,null)
    </td>
  </tr>
  <tr>
  <td colspan='2'><input type='submit' value="Submit"/></td>
  </tr>
</table>
</form>

Zero-K.info/Views/Planetwars/Events.cshtml
@using ZkData
@using ZeroKWeb
@model ZeroKWeb.Controllers.EventsResult
@if (Model.Partial) {
  Layout = null;
} else {
  Page.Title = "PlanetWars events";
}
@using (Ajax.BeginForm("Events", new { accountID = Model.AccountID, clanID = Model.ClanID, planetID = Model.PlanetID, springBattleID = Model.SpringBattleID, partial = Model.Partial, pageSize = Model.PageSize }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "events", LoadingElementId = "ajaxScrollProgress" })) {
  <div id='events'>
    @if (!Model.Partial) {
      <h3>
        PlanetWars events</h3>
    }
    <small>
      @Html.Hidden("page", Model.Page, new { id = "ev_page" })
      <table cellpadding='0' cellspacing='0'>
        <th>
          Time
        </th>
        <th>
          Event
        </th>
        @foreach (var e in Model.Events) {
          <tr>
            <td>@e.Time.ToAgoString()
            </td>
            <td>@Html.Raw(e.Text)
            </td>
          </tr>
        }
        <tr>
          <td>
            @if (Model.Page > 0) {
              <a href="#" onclick="$('#ev_page').val(parseInt($('#ev_page').val())-1); $('#ev_submit').click()">
                newer</a>
            }
            <span>&nbsp;|&nbsp</span>
            @if (Model.Page < Model.PageCount - 1) {
              <a href="#" onclick="$('#ev_page').val(parseInt($('#ev_page').val())+ 1); $('#ev_submit').click()">
                older</a>
            }
          </td>
          <td align="right">
          Page @(Model.Page+1) / @Model.PageCount <a href='@Url.Action("Events", "Planetwars", new { accountID = Model.AccountID, clanID = Model.ClanID, planetID = Model.PlanetID, springBattleID = Model.SpringBattleID, pageSize = int.MaxValue })'>all</a> | <a href='@Url.Action("Events", "Planetwars")'>unfiltered</a>
            @Html.TextBox("filter", Model.Filter)<input type="image" src="http://cdn1.iconfinder.com/data/icons/freeapplication/png/24x24/Filter.png" alt="filter events" value="filter" id="ev_submit" style="border: medium none; vertical-align:middle;" />
            
          </td>
        </tr>
      </table>
    </small>
  </div>
}

Zero-K.info/Views/Planetwars/GalaxyImage.cshtml
@model ZkData.Galaxy
         




Zero-K.info/Views/Planetwars/GalaxyOffline.cshtml
@model ZkData.Galaxy

<h2>Toasters are toast</h2>
<img src="http://i.imgur.com/BdyfBSd.png" /><br/>
<!-- http://i.imgur.com/0PAehPl.png -->

Humanity Rising swift attack took Hegemony by a fatal surprise. In what has been just a blink of an eye, forces of Rising completely eliminated Synthetic Hegemony, leaving no room for it to hide.<br/>
<br/>
Humans once again rule the world! Rogue AIs are disassembled or enslaved, elite cyborgs and uploads, who tried to defect and hide among true humans, captured and kept as GogoDancers and Drones.<br/><br/>
Old style democracies of Democratic Order Of Planets now control newly formed Federation. <br/>

<h3>Top clan</h3>
<a href="@Url.Action("Detail","Clans",new{id=803})">
    <img src="/img/clans/DOOP_bg.png" />
</a>
<br/>
<h3>Top players</h3>
<img src="http://i.imgur.com/JyAE9Qb.png" />

<h3>Galaxy</h3>
<img src="http://i.imgur.com/746U9rq.jpg" />