Zero-K.info/Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Transactions;
using System.Web.Mvc;
using ZkData;

namespace ZeroKWeb.Controllers
{
    public class CampaignController: Controller
    {
        //
        // GET: /Campaign/

        public Bitmap GenerateGalaxyImage(int campaignID, double zoom = 1, double antiAliasingFactor = 4) {
            zoom *= antiAliasingFactor;
            using (var db = new ZkDataContext()) {
                Campaign camp = db.Campaigns.Single(x => x.CampaignID == campaignID);

                using (Image background = Image.FromFile(Server.MapPath("/img/galaxies/" + camp.MapImageName))) {
                    Bitmap im = new Bitmap((int)(background.Width*zoom), (int)(background.Height*zoom));
                    using (Graphics gr = Graphics.FromImage(im)) {
                        gr.DrawImage(background, 0, 0, im.Width, im.Height);

                        foreach (CampaignPlanet p in camp.CampaignPlanets) {
                            string planetIconPath = null;
                            Resource map = db.Resources.FirstOrDefault(m => m.InternalName == p.Mission.Map);
                            try {
                                planetIconPath = "/img/planets/" + (map.MapPlanetWarsIcon ?? "1.png"); // backup image is 1.png
                                using (Image pi = Image.FromFile(Server.MapPath(planetIconPath))) {
                                    double aspect = pi.Height/(double)pi.Width;
                                    var width = (int)(map.PlanetWarsIconSize * zoom);
                                    var height = (int)(width*aspect);
                                    gr.DrawImage(pi, (int)(p.X*im.Width) - width/2, (int)(p.Y*im.Height) - height/2, width, height);
                                }
                            } catch (Exception ex) {
                                throw new ApplicationException(
                                    string.Format("Cannot process planet image {0} for planet {1} map {2}",
                                                  planetIconPath,
                                                  p.PlanetID,
                                                  map.ResourceID),
                                    ex);
                            }
                        }
                        if (antiAliasingFactor == 1) return im;
                        else {
                            zoom /= antiAliasingFactor;
                            return im.GetResized((int)(background.Width*zoom), (int)(background.Height*zoom), InterpolationMode.HighQualityBicubic);
                        }
                    }
                }
            }
        }

        [Auth]
        public ActionResult Index(int? campaignID = null)
        {
            var db = new ZkDataContext();

            Campaign camp;
            if (campaignID != null) camp = db.Campaigns.Single(x => x.CampaignID == campaignID);
            else camp = db.Campaigns.Single(x => x.CampaignID == 1);
            string cachePath = Server.MapPath(string.Format("/img/galaxies/campaign/render_{0}.jpg", camp.CampaignID));
            // /*
            if (camp.IsDirty || !System.IO.File.Exists(cachePath)) {
                using (Bitmap im = GenerateGalaxyImage(camp.CampaignID)) {
                    im.SaveJpeg(cachePath, 85);
                    camp.IsDirty = false;
                    camp.MapWidth = im.Width;
                    camp.MapHeight = im.Height;
                    db.SubmitChanges();
                }
            }
            // */
            return View("CampaignMap", camp);
        }

        public ActionResult Journals(int? campaignID = null)
        {
            if (Global.Account == null) return Content("You must be logged in to view campaign info");

            var db = new ZkDataContext();

            Campaign camp;
            if (campaignID != null) camp = db.Campaigns.Single(x => x.CampaignID == campaignID);
            else camp = db.Campaigns.Single(x => x.CampaignID == 1);

            return View("Journals", camp);
        }

        public ActionResult CampaignEvents(int? planetID,
                                   int? journalID,
                                   int campaignID,
                                   string filter,
                                   int pageSize = 0,
                                   int page = 0,
                                   bool partial = false)
        {
            int accountID = Global.AccountID;
            var db = new ZkDataContext();
            if (Request.IsAjaxRequest()) partial = true;
            if (pageSize == 0)
            {
                if (!partial) pageSize = 40;
                else pageSize = 10;
            }
            IQueryable<CampaignEvent> res = db.CampaignEvents.Where(x => x.AccountID == accountID && x.CampaignID == campaignID).AsQueryable();
            if (planetID.HasValue) res = res.Where(x => x.PlanetID == planetID);
            if (!string.IsNullOrEmpty(filter)) res = res.Where(x => x.Text.Contains(filter));
            res = res.OrderByDescending(x => x.EventID);

            var ret = new CampaignEventsResult
            {
                PageCount = (res.Count() / pageSize) + 1,
                Page = page,
                Events = res.Skip(page * pageSize).Take(pageSize),
                PlanetID = planetID,
                Filter = filter,
                Partial = partial,
                PageSize = pageSize
            };

            return View(ret);
        }

        /*
        public ActionResult Minimap() {
            var db = new ZkDataContext();

            return View(db.Galaxies.Single(g => g.IsDefault));
        }
         */

        [Auth]
        public ActionResult Planet(int id) {
            var db = new ZkDataContext();
            CampaignPlanet planet = db.CampaignPlanets.Single(x => x.PlanetID == id);
            return View(planet);
        }

    }

    #region Nested type: CampaignEventsResult

    public class CampaignEventsResult
    {
        public IQueryable<CampaignEvent> Events;
        public string Filter;
        public int Page;
        public int PageCount;
        public int PageSize;
        public bool Partial;
        public int? PlanetID;
    }

    #endregion
}

Zero-K.info/Controllers/MissionsController.cs
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Web.UI;
using ZkData;

namespace ZeroKWeb.Controllers
{
    public class MissionsController : Controller
    {
        //
        // GET: /Missions/
        

        [Auth(Role = AuthRole.ZkAdmin)]
        public ActionResult ChangeFeaturedOrder(int id, float? featuredOrder, string script)
        {
            var db = new ZkDataContext();
            var mis = db.Missions.SingleOrDefault(x => x.MissionID == id);
            mis.FeaturedOrder = featuredOrder;
            if (mis.IsScriptMission && !string.IsNullOrEmpty(script)) mis.Script = script;
            db.SubmitChanges();

            var order = 1;
            if (featuredOrder.HasValue) foreach (var m in db.Missions.Where(x => x.FeaturedOrder != null).OrderBy(x => x.FeaturedOrder)) m.FeaturedOrder = order++;
            db.SubmitChanges();

            return RedirectToAction("Index");
        }

        [Auth(Role = AuthRole.ZkAdmin | AuthRole.LobbyAdmin)]
        public ActionResult Delete(int id)
        {
            var db = new ZkDataContext();
            db.Missions.First(x => x.MissionID == id).IsDeleted = true;
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Detail(int id)
        {
            var db = new ZkDataContext();
            var mission = db.Missions.Single(x => x.MissionID == id);
            mission.ForumThread.UpdateLastRead(Global.AccountID, false);
            db.SubmitChanges();

            return View("Detail",
                        new MissionDetailData
                        {
                            Mission = mission,
                            TopScores = mission.MissionScores.OrderByDescending(x => x.Score).AsQueryable(),
                            MyRating = mission.Ratings.SingleOrDefault(x => x.AccountID == Global.AccountID) ?? new Rating(),
                        });
        }

        public ActionResult File(string name)
        {
            var id = 0;
            Mission m;
            var db = new ZkDataContext();
            if (int.TryParse(name, out id)) {
                m = db.Missions.Single(x => x.MissionID == id);
            } else m = db.Missions.Single(x => x.Name == name);
            return File(m.Mutator.ToArray(), "application/octet-stream", m.SanitizedFileName);
        }

        public ActionResult Index(string search, int? offset, bool? sp, bool? coop, bool? adversarial, bool? featured)
        {
            if (featured == null) featured = true;

            var db = new ZkDataContext();
            if (!offset.HasValue)
            {
                return
                    View(new MissionsIndexData()
                         {
                             Title = "Latest missions",
                             LastUpdated = FilterMissions(db.Missions, search, featured).Take(Global.AjaxScrollCount),
                             MostPlayed =
                                 db.Missions.Where(
                                     x =>
                                     !x.IsDeleted &&
                                     (featured == false || x.ModRapidTag.StartsWith("zk:") || x.Mod.StartsWith("Zero-K") ||
                                      x.Mod.StartsWith("Complete"))).OrderByDescending(x => x.MissionRunCount),
                             MostRating =
                                 db.Missions.Where(
                                     x =>
                                     !x.IsDeleted &&
                                     (featured == false || x.ModRapidTag.StartsWith("zk:") || x.Mod.StartsWith("Zero-K") ||
                                      x.Mod.StartsWith("Complete"))).OrderByDescending(x => x.Rating),
                             LastComments =
                                 db.Missions.Where(
                                     x =>
                                     !x.IsDeleted &&
                                     (featured == false || x.ModRapidTag.StartsWith("zk:") || x.Mod.StartsWith("Zero-K") ||
                                      x.Mod.StartsWith("Complete"))).OrderByDescending(x => x.ForumThread.LastPost),
                             SearchString = search,
                         });
            }

            else
            {
                var mis = FilterMissions(db.Missions, search, featured.Value, offset, sp, coop, adversarial).Take(Global.AjaxScrollCount);
                if (mis.Any()) return View("TileList", mis);
                else return Content("");
            }
        }

        [Auth]
        public ActionResult Rate(int id, int? difficulty, int? rating)
        {
            var db = new ZkDataContext();
            var rat = db.Ratings.SingleOrDefault(x => x.MissionID == id && x.AccountID == Global.Account.AccountID);
            if (rat == null)
            {
                rat = new Rating();
                db.Ratings.InsertOnSubmit(rat);
            }
            rat.MissionID = id;
            rat.AccountID = Global.Account.AccountID;
            if (difficulty.HasValue) rat.Difficulty = difficulty;
            if (rating.HasValue) rat.Rating1 = rating;
            db.SubmitChanges();

            var mis = db.Missions.Single(x => x.MissionID == id);
            mis.Rating = (float?)mis.Ratings.Average(x => x.Rating1);
            mis.Difficulty = (float?)mis.Ratings.Average(x => x.Difficulty);
            db.SubmitChanges();

            return Content("");
        }


        public ActionResult Script(int id)
        {
            var m = new ZkDataContext().Missions.Single(x => x.MissionID == id);
            return File(Encoding.UTF8.GetBytes(m.Script), "application/octet-stream", "script.txt");
        }

        [Auth(Role = AuthRole.ZkAdmin | AuthRole.LobbyAdmin)]
        public ActionResult Undelete(int id)
        {
            var db = new ZkDataContext();
            db.Missions.First(x => x.MissionID == id).IsDeleted = false;
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        static IQueryable<Mission> FilterMissions(IQueryable<Mission> ret,
                                                  string search,
                                                  bool? featured,
                                                  int? offset = null,
                                                  bool? sp = null,
                                                  bool? coop = null,
                                                  bool? adversarial = null)
        {
            if (featured == null) featured = true;

            ret =
                ret.Where(
                    x =>
                    !x.IsDeleted &&
                    (featured == false || x.ModRapidTag.StartsWith("zk:") || x.Mod.StartsWith("Zero-K") || x.Mod.StartsWith("Complete")));
            if (featured == true) ret = ret.Where(x => x.FeaturedOrder > 0);
            if (sp == false) ret = ret.Where(x => x.MaxHumans > 1);
            if (coop == false) ret = ret.Where(x => (x.MinHumans <= 1 && sp == true) || x.MaxHumans > 1 && !x.IsCoop);
            if (adversarial == false) ret = ret.Where(x => (x.MinHumans <= 1 && sp == true) || (x.MaxHumans > 1 && x.IsCoop));
            if (!string.IsNullOrEmpty(search)) ret = ret.Where(x => x.Name.Contains(search) || x.Account.Name.Contains(search));

            if (featured == true) ret = ret.OrderByDescending(x => -x.FeaturedOrder).ThenByDescending(x => x.ModifiedTime);
            else ret = ret.OrderByDescending(x => x.ModifiedTime);
            if (offset != null) ret = ret.Skip(offset.Value);

            return ret;
        }
    }

    public class MissionDetailData
    {
        public Mission Mission;
        public Rating MyRating;
        public IQueryable<MissionScore> TopScores;
    }

    public class MissionsIndexData
    {
        public IQueryable<Mission> LastComments;
        public IQueryable<Mission> LastUpdated;
        public IQueryable<Mission> MostPlayed;
        public IQueryable<Mission> MostRating;
        public string SearchString;
        public string Title;
    }
}

Zero-K.info/Views/Campaign/CampaignEvents.cshtml
@using ZkData
@using ZeroKWeb
@model ZeroKWeb.Controllers.CampaignEventsResult
@if (Model.Partial) {
  Layout = null;
} else {
  Page.Title = "Campaign Events";
}
@using (Ajax.BeginForm("CampaignEvents", new { planetID = Model.PlanetID, partial = Model.Partial, pageSize = Model.PageSize }, new AjaxOptions() { InsertionMode = InsertionMode.Replace, UpdateTargetId = "events", LoadingElementId = "ajaxScrollProgress" })) {
  <div id='events'>
    @if (!Model.Partial) {
      <h3>
        Campaign Events</h3>
    }
    <small>
      @Html.Hidden("page", Model.Page, new { id = "ev_page" })
      <table cellpadding='0' cellspacing='2'>
        <th>
          Time
        </th>
        <th>
          Event
        </th>
        @foreach (var e in Model.Events) {
          <tr>
            <td>@e.Time.ToString()
            </td>
            <td>@Html.Raw(e.Text)
            </td>
          </tr>
        }
        <tr>
          <td>
            @if (Model.Page > 0) {
              <a href="#" onclick="$('#ev_page').val(parseInt($('#ev_page').val())-1); $('#ev_submit').click()">
                newer</a>
            }
            <span>&nbsp;|&nbsp</span>
            @if (Model.Page < Model.PageCount - 1) {
              <a href="#" onclick="$('#ev_page').val(parseInt($('#ev_page').val())+ 1); $('#ev_submit').click()">
                older</a>
            }
          </td>
          <td align="right">
          Page @(Model.Page+1) / @Model.PageCount <a href='@Url.Action("CampaignEvents", "Campaign", new { planetID = Model.PlanetID, pageSize = int.MaxValue })'>all</a> | <a href='@Url.Action("CampaignEvents", "Campaign")'>unfiltered</a>
            @Html.TextBox("filter", Model.Filter)<input type="image" src="http://cdn1.iconfinder.com/data/icons/freeapplication/png/24x24/Filter.png" alt="filter events" value="filter" id="ev_submit" style="border: medium none; vertical-align:middle;" />
            
          </td>
        </tr>
      </table>
    </small>
  </div>
}

Zero-K.info/Views/Campaign/CampaignMap.cshtml
@using ZeroKWeb
@using ZkData
@model Campaign
@{
    Page.Title = "Campaign " + Model.Name + " - Galaxy Map";
	ViewBag.Minimal = true;
    var db = new ZkDataContext();
	Campaign camp = Model;
}

@* Planet link lines *@

@functions {
}

@section head {
	<script type="text/javascript">
		/*
		window.onload = function () */
		$(document).ready(function()
		{
			var paper = Raphael(document.getElementById("linkMap"), @Model.MapWidth, @Model.MapHeight);

            @foreach (CampaignLink link in Model.CampaignLinks)
            { 
                CampaignPlanet p1 = link.PlanetToUnlock;
                CampaignPlanet p2 = link.UnlockingPlanet;

                var x1 = p1.X * Model.MapWidth;
                var y1 = p1.Y * Model.MapHeight;
                var x2 = p2.X * Model.MapWidth;
                var y2 = p2.Y * Model.MapHeight;
          
                // lines don't support gradients, so use rectangles instead
				double width = 2;
				var color1 = p1.GetColor(Global.Account);
				var color2 = p2.GetColor(Global.Account);
				var angle = -Math.Atan2(x2 - x1, y2 - y1) / Math.PI * 180;
				var length = Math.Sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1));
				var lineX = x1 - width / 2;
				var lineY = y1 + width / 2;

				// don't let the line cover the planets
                string mapName1 = p1.DisplayedMap ?? p1.Mission.Map;
                string mapName2 = p2.DisplayedMap ?? p1.Mission.Map;
                Resource map1 = db.Resources.FirstOrDefault(m => m.InternalName == mapName1);
                Resource map2 = db.Resources.FirstOrDefault(m => m.InternalName == mapName2);
				lineY += map1.PlanetWarsIconSize / 2 * 1.5;
				length -= map2.PlanetWarsIconSize * 1.5;

				@: var r = paper.rect(@String.Format("{0:0}, {1:0}, {2:0}, {3:0}", lineX, lineY, width, length));
				@: r.attr({
				@:	"fill": "90-@color2-@color1",
				@:	"stroke": "none"
				@: });
				@: r.rotate(@angle, @String.Format("{0:0}", x1), @String.Format("{0:0}", y1));
            } 
		} )
	</script>
}
<br />

<h1 style="color:Red">Campaign is in alpha stage. Please report errors.</h1>
<br style="clear:both"/>
<br class="clearfloat" />

<div class="">
    <h3>@Html.ActionLink("Journals", "Journals")</h3>
</div>
<br />

<div style="position: relative; z-index: 100" >
	<div id="linkMap" style="position: absolute; z-index: 0"> </div>
    <img src="/img/galaxies/campaign/render_@(camp.CampaignID).jpg" style="position: relative; top: 0; left: 0; z-index:-50; " width="@Model.MapWidth" height="@Model.MapHeight"/>
	

@foreach (CampaignPlanet p in Model.CampaignPlanets)
{
	var pr = p.PlanetRectangle(Model);
	var por = p.PlanetOverlayRectangle(Model);
	<div style="position: absolute; left: @(por.Left)px; top: @(por.Top)px; width: @(por.Width)px; height: @(por.Height)px; font-size: 12px; font-weight: bold; " >
		<table style="position: absolute; border: 0; padding: 0; text-align: center; font-size: 10px; z-index: 5; line-height: .85; width:100%; height:25%;"><tr>
		<td style="vertical-align: bottom;" ><div style="display:inline-block;">
            @if(p.IsUnlocked(Global.AccountID)) {
                <a href='@Url.Action("Planet", new { id = p.PlanetID })' nicetitle="$campaignPlanet$@p.PlanetID" style="color: #ffffff; color: @p.GetColor(Global.Account)">@p.Name<br /></a>
            }
            else
            {
                <span nicetitle="$campaignPlanet$@p.PlanetID" style="color: #ffffff; color: @p.GetColor(Global.Account)">@p.Name<br /></span>
            }
		</div></td></tr></table>
	</div>
}

</div>

<div>
    <h3>Last events</h3>
	<span style='float:left'>
	@Html.Action("CampaignEvents", new { partial = true, pageSize = 40, campaignID = camp.CampaignID })</span>
	<span><img	src='http://3.bp.blogspot.com/_YTJBDUN8iSE/TSjDkNEwJAI/AAAAAAAAD0o/N8w-cy_J_EM/s1600/Tracy_Caldwell_Dyson_in_Cupola_ISS.jpg' width='600' /><br /> Please forgive and report issues :-)</span>
</div>

Zero-K.info/Views/Campaign/CampaignPlanet.cshtml
@using PlasmaShared
@using ZkData
@using ZeroKWeb
@model CampaignPlanet
@{
	ViewBag.Title = "Planet";
	Page.Title = "Planet " + Model.Name;
	var db = new ZkDataContext();
    var colorStyle = "";
    Account account = Global.Account;
    var progress = db.AccountCampaignProgress.First(x=> x.AccountID == account.AccountID);
    bool unlocked = progress != null && progress.IsUnlocked == true;
    if (unlocked) {
        colorStyle = "color:#88FF88;";
    }
}
<h1 style="@colorStyle">
    Planet @Model.Name
</h1>
<table>
	<tr>
		<td>
			@Html.Partial("PlanetIcon", Model)
		</td>
		<td>
			@Html.Partial("MapInfoBox", Model.Mission.Resources)
		</td>
	</tr>
</table>
@{
	var campaign = db.Campaigns.FirstOrDefault(c => c.CampaignID == Model.CampaignID);
	var mapWidth = 700;
	var mapHeight = 500;
}
@section head {
	<script type="text/javascript">
		$(document).ready(function () {
			$("#tabs").tabs();
		});
	</script>
	<script type="text/javascript">
        window.onload = function () 
        {
            var paper = Raphael(document.getElementById("minimap"), @mapWidth, @mapHeight);

            @foreach (var link in Model.CampaignLinks)
            { 
                var p1 = db.CampaignPlanets.First(x => x.PlanetID == link.PlanetToUnlock);
                var p2 = db.CampaignPlanets.First(x => x.PlanetID == link.UnlockingPlanet);

                var x1 = p1.X * mapWidth;
                var y1 = p1.Y * mapHeight;
                var x2 = p2.X * mapWidth;
                var y2 = p2.Y * mapHeight;
          
                var width = 2;
                var color1 = p1.GetColor(Global.Account);
                var color2 = p2.GetColor(Global.Account);
                var angle = -Math.Atan2(x2 - x1, y2 - y1) / Math.PI * 180;
                var length = Math.Sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1));
                @: var r = paper.rect(@x1-@width/2, @y1, @width, @length);
                @: r.attr({
                @:  "fill": "90-@color2-@color1",
                @:  "stroke": "none",
                @: });
                @: r.rotate(@angle, @x1, @y1);
            } 

            @foreach (var planet in campaign.CampaignPlanets) {
							var mapIconSize = 10;
							var stroke = "#000000";
							if (planet.PlanetID == Model.PlanetID) {
								mapIconSize *= 2;
								stroke = "#ffffff";
							}
                @: var circle = paper.circle(@(planet.X * mapWidth), @(planet.Y * mapHeight), @mapIconSize);
                @: circle.attr({
                @:  "fill": "@planet.GetColor(Global.Account)",
                @:  "stroke": "@stroke",
                @:  "stroke-width": "3"
                @: });
            }
        };
	</script>
}

Zero-K.info/Views/Campaign/Planet.cshtml
@using ZkData
@using ZeroKWeb
@model CampaignPlanet
@{
	ViewBag.Title = "Planet";
	Page.Title = "Planet " + Model.Name;
	ZkDataContext db = new ZkDataContext();
    string mapName = Model.DisplayedMap ?? Model.Mission.Map;
    Resource map = db.Resources.FirstOrDefault(m => m.InternalName == mapName);
    bool complete = Model.IsCompleted(Global.AccountID);
    bool unlocked = Model.IsUnlocked(Global.AccountID);
    string colorStyle = "color:" + Model.GetColor(Global.Account) + ";";
    var journalsRaw = db.CampaignJournals.Where(x => x.CampaignID == Model.CampaignID && x.PlanetID == Model.PlanetID).ToList();
    var journals = journalsRaw.Where(x => x.IsUnlocked(Global.AccountID)).ToList();
    
    Campaign campaign = db.Campaigns.Single(c => c.CampaignID == Model.CampaignID);
    int mapWidth = 700;
    var mapHeight = 500;
}
@section head {
    <script type="text/javascript" src='@Href("~/Scripts/jquery.expand.js")' > </script>
    <script type="text/javascript">
        $(function () {
            $("h4.expand").toggler({ speed: 0 });
        });
    </script>
	<script type="text/javascript">
	    $(document).ready(function () {
	        $("#tabs").tabs();
	    });
	</script>
	<script type="text/javascript">
        window.onload = function () 
        {
            var paper = Raphael(document.getElementById("minimap"), @mapWidth, @mapHeight);
            @foreach (CampaignLink link in Model.CampaignLinksByPlanetToUnlock)
            {
                CampaignPlanet p1 = link.PlanetToUnlock;
                CampaignPlanet p2 = link.UnlockingPlanet;

                var x1 = p1.X * mapWidth;
                var y1 = p1.Y * mapHeight;
                var x2 = p2.X * mapWidth;
                var y2 = p2.Y * mapHeight;

                var width = 2;
                var color1 = p1.GetColor(Global.Account);
                var color2 = p2.GetColor(Global.Account);
                var angle = -Math.Atan2(x2 - x1, y2 - y1) / Math.PI * 180;
                var length = Math.Sqrt((x2 - x1) * (x2 - x1) + (y2 - y1) * (y2 - y1));
                @: var r = paper.rect(@x1-@width/2, @y1, @width, @length);
                @: r.attr({
                @:  "fill": "90-@color2-@color1",
                @:  "stroke": "none",
                @: });
                @: r.rotate(@angle, @x1, @y1);
            } 

            @foreach (CampaignPlanet planet in campaign.CampaignPlanets)
            {
                var mapIconSize = 10;
                var stroke = "#000000";
                if (planet.PlanetID == Model.PlanetID)
                {
                    mapIconSize *= 2;
                    stroke = "#8888FF";
                }
                @: var circle = paper.circle(@(planet.X * mapWidth), @(planet.Y * mapHeight), @mapIconSize);
                @: circle.attr({
                @:  "fill": "@planet.GetColor(Global.Account)",
                @:  "stroke": "@stroke",
                @:  "stroke-width": "3"
                @: });
            }
        };
	</script>   
)}


<h1 style="@colorStyle">
    Planet @Model.Name
</h1>
<table>
	<tr>
		<td>
			@Html.Partial("PlanetIconCampaign", Model)
		</td>
		<td>
			@Html.Partial("MapInfoBox", map)
		</td>
	</tr>
</table>
@Html.BBCode(@Model.Description)
<br /><br />
@if (unlocked){
    <h3>Mission: @Html.ActionLink(Model.Mission.Name, "Detail", "Missions", new { id = Model.MissionID }, null)</h3>
    if (Model.DescriptionStory != null) {
        <br />
        @Html.BBCode("\t"+Model.DescriptionStory)
    }
}
<br />

@if (journals != null && journals.Count > 0)
{
    <br />
    <h3>Journals</h3>
    <div id="journals" class="journal">
        @foreach (CampaignJournal journal in journals)
        {
            <h4 class="expand">@journal.Title</h4>
            <div id="@journal.Title" class="collapse width-90">
                @Html.BBCode(journal.Text)
            </div>
        }
    </div>
}