Zero-K.info/Controllers/PollController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ZkData;

namespace ZeroKWeb.Controllers
{
    public class PollController : Controller
    {
        //
        // GET: /Poll/

        public ActionResult Index(int pollID)
        {
            var db = new ZkDataContext();
            var poll = db.Polls.FirstOrDefault(x => x.PollID == pollID);
            if (poll != null) return PartialView("PollView", poll);
            return null;
        }

        [Auth(Role = AuthRole.ZkAdmin)]
        public ActionResult NewPoll(string question, string answers, bool? isAnonymous)
        {
            var p = new Poll() { CreatedAccountID = Global.AccountID, IsHeadline = true, QuestionText = question, IsAnonymous = isAnonymous == true, };
            var db = new ZkDataContext();

            foreach (var a in answers.Split(new char[] { '\n' }, StringSplitOptions.RemoveEmptyEntries)) p.PollOptions.Add(new PollOption() { OptionText = a });

            db.Polls.InsertOnSubmit(p);
            db.SubmitChanges();
            return RedirectToAction("UserVotes", new { id = Global.AccountID });
        }

        public static void AutoClosePolls()
        {
            var db = new ZkDataContext();
            foreach (var p in db.Polls.Where(x => x.IsHeadline && x.ExpireBy != null && x.ExpireBy < DateTime.UtcNow && x.RoleTypeID != null).ToList())
            {
                var yes = p.PollVotes.Count(x => x.PollOption.OptionText == "Yes");
                var no = p.PollVotes.Count(x => x.PollOption.OptionText == "No");
                var acc = p.AccountByRoleTargetAccountID;
                if (yes > no)
                {
                    if (p.RoleIsRemoval)
                    {
                        var toDelete = db.AccountRoles.Where(x => x.AccountID == acc.AccountID && x.RoleTypeID == p.RoleTypeID);
                        db.AccountRoles.DeleteAllOnSubmit(toDelete);
                        db.Events.InsertOnSubmit(Global.CreateEvent("{0} was removed from the {1} role of {2} by a vote - {3} for, {4} against", acc, (object)p.Clan ?? p.Faction, p.RoleType, yes, no));

                        db.SubmitAndMergeChanges();

                        AuthServiceClient.SendLobbyMessage(acc, string.Format("You were recalled from the function of {0} by a vote", p.RoleType.Name));
                    }
                    else
                    {
                        if (!acc.AccountRolesByAccountID.Any(x => x.RoleTypeID == p.RoleTypeID))
                        {
                            Account previous = null;
                            if (p.RoleType.IsOnePersonOnly)
                            {
                                var entries = db.AccountRoles.Where(x => x.RoleTypeID == p.RoleTypeID && (p.RoleType.IsClanOnly ? x.ClanID == p.RestrictClanID : x.FactionID == p.RestrictFactionID)).ToList();

                                if (entries.Any())
                                {
                                    previous = entries.First().Account;
                                    db.AccountRoles.DeleteAllOnSubmit(entries);
                                    db.SubmitAndMergeChanges();
                                }
                            }

                            var entry = new AccountRole()
                                        {
                                            Account = acc,
                                            Inauguration = DateTime.UtcNow,
                                            Clan = p.Clan,
                                            Faction = p.Faction,
                                            RoleType = p.RoleType
                                        };
                            acc.AccountRolesByAccountID.Add(entry);
                            if (previous == null)
                                db.Events.InsertOnSubmit(Global.CreateEvent("{0} was elected for the {1} role of {2} by a vote - {3} for, {4} against",
                                                   acc,
                                                   (object)p.Clan ?? p.Faction,
                                                   p.RoleType,
                                                   yes,
                                                   no));

                            else db.Events.InsertOnSubmit(Global.CreateEvent("{0} was elected for the {1} role of {2} by a vote, replacing {3} - {4} for, {5} against",
                                                   acc,
                                                   (object)p.Clan ?? p.Faction,
                                                   p.RoleType,
                                                   previous,
                                                   yes,
                                                   no));

                            AuthServiceClient.SendLobbyMessage(acc, string.Format("Congratulations!! You were elected into a function of {0} by a vote", p.RoleType.Name));
                        }
                    }
                }

                p.IsHeadline = false;
                db.Polls.DeleteOnSubmit(p);
            }
            db.SubmitAndMergeChanges();
        }



        [Auth()]
        public ActionResult NominateRole(int roleTypeID, string text, bool isRemoval = false, int? removalAccountID = null)
        {
            var db = new ZkDataContext();
            var pollActive = Global.Account.PollsByRoleTargetAccountID.Any(x => x.ExpireBy > DateTime.UtcNow);
            if (pollActive) return Content("Poll already active, wait until it ends");

            var rt = db.RoleTypes.Single(x => x.RoleTypeID == roleTypeID);

            if (!rt.IsClanOnly && GlobalConst.PlanetWarsMode == PlanetWarsModes.AllOffline) return Content("Round over, no nominations can be made");
            if (rt.RestrictFactionID != null && rt.RestrictFactionID != Global.FactionID) throw new ApplicationException("Invalid faction");
            if (!rt.IsClanOnly && Global.FactionID == 0) throw new ApplicationException("No faction");
            if (!rt.IsClanOnly && rt.Faction.IsDeleted) throw new ApplicationException("Disabled faction");
            if (rt.IsClanOnly && Global.ClanID == 0) throw new ApplicationException("No clan");
            if (!rt.IsVoteable) throw new ApplicationException("Cannot be voted");

            int targetID = Global.AccountID;
            if (isRemoval)
            {
                var target = db.Accounts.Single(x => x.AccountID == removalAccountID);
                if (Global.Account.CanVoteRecall(target, rt))
                {
                    targetID = removalAccountID.Value;
                }
                else
                {
                    return Content("Cannot recall him/her");
                }
            }

            var p = new Poll()
                    {
                        CreatedAccountID = Global.AccountID,
                        RoleTargetAccountID = targetID,
                        ExpireBy = DateTime.UtcNow.AddDays(rt.PollDurationDays),
                        IsAnonymous = true,
                        IsHeadline = true,
                        RoleIsRemoval = isRemoval,
                        RoleType = rt,
                        RestrictClanID = rt.IsClanOnly ? Global.Account.ClanID : null,
                        RestrictFactionID = rt.IsClanOnly ? null : Global.Account.FactionID,
                        QuestionText = text
                    };
            p.PollOptions.Add(new PollOption() { OptionText = "Yes" });
            p.PollOptions.Add(new PollOption() { OptionText = "No" });
            db.Polls.InsertOnSubmit(p);
            db.SubmitChanges();
            return RedirectToAction("Detail", "Users", new { id = Global.AccountID });
        }

        [Auth]
        public ActionResult PollVote(int pollID)
        {
            var key = Request.Form.AllKeys.Where(x => !string.IsNullOrEmpty(x)).First(x => x.StartsWith("option"));
            var optionID = Convert.ToInt32(key.Substring(6));

            var db = new ZkDataContext();
            var poll = Global.Account.ValidPolls(db).Single(x => x.PollID == pollID);

            if (!poll.PollOptions.Any(x => x.OptionID == optionID)) return Content("Invalid option");

            var entry = poll.PollVotes.SingleOrDefault(x => x.AccountID == Global.AccountID);
            if (entry == null)
            {
                entry = new PollVote() { PollID = poll.PollID, AccountID = Global.AccountID };
                poll.PollVotes.Add(entry);
            }
            entry.OptionID = optionID;

            db.SubmitChanges();
            foreach (var opt in poll.PollOptions) opt.Votes = opt.PollVotes.Count(x => x.PollID == poll.PollID);
            db.SubmitChanges();

            return PartialView("PollView", poll);
        }

        [Auth(Role = AuthRole.ZkAdmin)]
        public ActionResult SwapHeadline(int pollid)
        {
            var db = new ZkDataContext();
            var p = db.Polls.Single(x => x.PollID == pollid);
            p.IsHeadline = !p.IsHeadline;
            db.SubmitChanges();
            ;
            return RedirectToAction("UserVotes", new { id = Global.AccountID });
        }

        public ActionResult UserVotes(int id)
        {
            var db = new ZkDataContext();
            var acc = db.Accounts.Single(x => x.AccountID == id);
            return View("PollUserVotes", acc);
        }
    }
}

Zero-K.info/Views/Poll/PollUserRoles.cshtml
@using ZeroKWeb
@using ZkData
@model ZkData.Account

@foreach (var entry in Model.AccountRolesByAccountID) {
    <span>
        @Html.PrintRoleType(entry.RoleType) of @(entry.RoleType.IsClanOnly ? Html.PrintClan(entry.Clan) : Html.PrintFaction(entry.Faction,false))
    </span>
    if (Global.Account.CanVoteRecall(entry.AccountByAccountID, entry.RoleType)) {
        <a href="@Url.Action("NominateRole", "Poll", new { roleTypeID = entry.RoleTypeID, isRemoval = true })" onclick="var text = prompt('What is the reason?', 'He failed us!'); $(this).attr('href', $(this).attr('href') + '&text=' + text);">(vote out)</a>
     }
      <span>&nbsp;</span>
     if (Global.Account.CanRecall(entry.AccountByAccountID, entry.RoleType)) {
         <a href="@Url.Action("RecallRole", "Planetwars", new { accountID = entry.AccountID, roleTypeID = entry.RoleTypeID })">(recall)</a>
     }
    <br/>
}
@if (Model.FactionID != null && Model.FactionID == Global.FactionID)
{
    foreach (var grp in new ZkDataContext().RoleTypes.Where(x => (x.RestrictFactionID == null || x.RestrictFactionID == Global.FactionID) && !x.AccountRoles.Any(y=>y.AccountID == Model.AccountID)).GroupBy(x => x.IsClanOnly)) {
        
        if (!grp.Key)
        {
            <span>Possible faction roles: </span>
        }
        else {
            <span>Possible clan roles: </span>
        }
        <small>
        @foreach (var role in grp)
        {
            @Html.PrintRoleType(role)

            if (role.IsVoteable && Global.AccountID == Model.AccountID) {
            <a href="@Url.Action("NominateRole", "Poll", new { roleTypeID = role.RoleTypeID })" onclick="var text = prompt('What is your slogan?', 'vote me!'); $(this).attr('href', $(this).attr('href') + '&text=' + text);">(nominate)</a>    
            }
            if (Global.Account.CanAppoint(Model, role)) {
                <a href="@Url.Action("AppointRole","Planetwars", new {accountID = Model.AccountID, roleTypeID = role.RoleTypeID})">(appoint)</a>
            }

            <span>,&nbsp;&nbsp;</span>
        }
       </small><br/>
    }
}

Zero-K.info/Views/Poll/PollUserVotes.cshtml
@using ZeroKWeb
@model ZkData.Account
<h2>Voting details for @Html.PrintAccount(Model)</h2>

@foreach (var p in Model.ValidPolls().OrderByDescending(x => x.PollID))
{
    <div style="@(p.IsHeadline ? " border: 1px solid green" : ""); margin:2px; padding:1px">
    @Html.Partial("PollView", p)

    @if (!p.IsAnonymous)
    {
        var vote = p.PollVotes.FirstOrDefault(x => x.AccountID == Model.AccountID);
        if (vote != null)
        {
            if (!p.IsAnonymous)
            {
                <span>Voted: @vote.PollOption.OptionText</span>
            }
            else
            {
                <span>Voted</span>
            }
        }
    }

    @if ((Global.IsZeroKAdmin || Global.IsLobbyAdmin) && p.ExpireBy == null)
    {   

            <br/>
            @Html.ActionLink(p.IsHeadline ? "STOP displaying" : "start displaying", "SwapHeadline", new { pollID = p.PollID })<br />
    }
    </div>
}

@if (Global.IsZeroKAdmin || Global.IsLobbyAdmin)
{
    <div class="admin">
        <h3>Add a new poll</h3>
        <form action="@Url.Action("NewPoll")" method="POST">
            Is anonymous: <input type="checkbox" name="isAnonymous" value="true" /><br/>
            Question: <br/>
            <input type="text" name="question" style="width: 600px"/><br/>
            Answers (one per line):<br/>
            <textarea name="answers" rows="6" style="width: 600px"></textarea><br/>
            <input type="submit" value="add" class="delete" />

        </form>
    </div>
}

Zero-K.info/Views/Poll/PollView.cshtml
 @using ZkData
@model Poll
@{
    var p = Model;
    var divID = "pollForm" + p.PollID;
  var maxVotes = p.PollOptions.Sum(x => x.Votes);
  if (maxVotes == 0) {
	maxVotes = 1;
  }
  
  }
@using (Ajax.BeginForm("PollVote", new { pollID = @p.PollID }, new AjaxOptions() { UpdateTargetId = divID, InsertionMode = InsertionMode.Replace, HttpMethod = "post", LoadingElementId = "ajaxScrollProgress" }))
{

    <div id="@divID">
        @if (Model.RoleType != null)
        {
            <h4>@(Model.RoleIsRemoval ? "Recall" : "Elect") @Html.PrintAccount(Model.AccountByRoleTargetAccountID)    
                @if (Model.Clan != null)
                {
                    @Html.PrintClan(Model.Clan)
                }
                else
                {
                    @Html.PrintFaction(Model.Faction, false)
                }
                @Html.PrintRoleType(Model.RoleType) ?<br />
                @p.QuestionText
            </h4>
        }
        else
        {
            <h4>@Html.BBCode(p.QuestionText)</h4>
        }
        @if (p.IsAnonymous) {
            <span>(anonymous poll)</span>
        }
        <small>
            <table>
                @foreach (var option in p.PollOptions)
                { 
                    <tr>
                        <td>
                            <input type="submit" name="option@(option.OptionID)" value="Vote" 
                                   title="@(p.IsAnonymous? "":"$polloption$" +option.OptionID)" 
						
                                />
                        </td>
                        <td>
                            @Html.BBCode(option.OptionText)
                        </td>
                        <td>
                            @Math.Round(100.0 * option.Votes / maxVotes)% (@option.Votes)
                        </td>
                        <td>
                            <img src='/img/bar_blue_poll.png' alt="@Math.Round(100.0 * option.Votes / maxVotes)%" width='@(150 * option.Votes / maxVotes)' height='10px'/>
                        </td>
                    </tr>
                }
                <tr><td align="center">-----</td><td align="center">(Total votes: @maxVotes)</td><td align="center">-----</td>
                </tr>
            </table>
        </small>
    </div>
}

Zero-K.info/Views/Poll/PollVoteList.cshtml
@model IEnumerable<ZkData.Account>
         
<span>
<small>
Level sum: @Model.Sum(x => (int?)x.Level), level avg: @Math.Round(Model.Average(x => (int?)x.Level)??0), elo avg: @Math.Round(Model.Average(x => (double?)x.EffectiveElo)??0)) <br />

@foreach (var a in Model.OrderByDescending(x=>x.Level).Take(30)) {
  @Html.PrintAccount(a)<br />
}
</small>
</span>
